### ISSUE TITLE
Use `Data.Text.commonPrefixes`?

### ISSUE THREAD

**Issue by Bodigrim** [mrkkrp/text-metrics#22]
Just curious: is there a specific reason to prefer `commonPrefix` instead of using built-in [`Data.Text.commonPrefixes`](https://hackage.haskell.org/package/text-1.2.5.0/docs/Data-Text.html#v:commonPrefixes)?

https://github.com/mrkkrp/text-metrics/blob/f04f42dab3056ebe2c67bbf4f02be52c816d1f0b/Data/Text/Metrics.hs#L350-L362

(I'm testing `text-metrics` with `text-2.0`, which implements a faster `commonPrefixes` than `text-1.2.5.0`)

**Comment by mrkkrp** [comment]
Applied as part of #23.
